version: '3.8'
services:
  feature_flag:
    container_name: feature_flag
    build: . # Chamada do DockerFile
    restart: always
    ports:
      - 3500:80
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=postgres;Port=5433;Database=featureflag;Username=admin;Password=admin"
    networks:
      - env_local
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres_feature_flag
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: featureflag
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - env_local

  redis:
    image: redis:latest
    container_name: redis_feature_flag
    restart: always
    ports:
      - 6380:6379
    networks:
      - env_local

networks:
  env_local:
    driver: bridge

volumes:
  postgres_data:
